name: CORA
ami: ami-05865edb0dba554ff
scripts_dir: .
manual_installation_step: False
run_installation_script_as_root: False
run_post_installation_script_as_root: False
run_toolkit_as_root: False
description: >
  The Continuous Reachability Analyzer (CORA) is a collection of MATLAB classes for the formal verification of cyber-physical systems using reachability analysis. CORA integrates various vector and matrix set representations and operations on them as well as reachability algorithms of various dynamic system classes. The software is designed such that set representations can be exchanged without having to modify the code for reachability analysis. CORA is designed using the object oriented paradigm, such that users can safely use methods without concerning themselves with detailed information hidden inside the object. Since the toolbox is written in MATLAB, the installation and use is platform independent. 
  
  CORA enables the formal verification of neural networks, both in open-loop as well as in closed loop scenarios. Open-loop verification refers to the task where properties of the output set of a neural network are verified, e.g. correctly classified images given noisy input. In closed-loop scenarios, the neural network is used as controller of a dynamic system and is neatly integrated in the reachability algorithms of CORA, e.g. controlling a car while keeping a safe distance.

  TODO: ADD REFERENCES
